apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-backend
  template:
    metadata:
      labels:
        app: sentiment-backend
    spec:
      containers:
      - name: sentiment-backend
        image: atharvaramawat/sentiment-backend:latest
        ports:
        - containerPort: 5000 
