version: '3.8'
services:
  backend:
    build: ./backend
    container_name: sentiment-backend
    ports: 
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: sentiment-frontend
    ports:
      - "8501:8501"
    environment : 
      - BACKEND_URL=http://backend:8000
    depends_on : 
      - backend
